[project]
name = "pyprodtest"
version = "0.1.0"
description = "Pytest plugin for production testing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "jinja2>=3.1.6",
    "pyyaml>=6.0.2",
    "pytest>=8.4.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.12",
]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.setuptools.package-data]
"_pyprodtest.observers.html_report" = ["templates/*.html"]
"_pyprodtest.web_assets" = ["*.css"]
"_pyprodtest.observers.web_ui" = ["templates/*.html", "static/*.js"]

[project.entry-points.pytest11]
pyprodtest = "_pyprodtest.hooks"
