[project]
name = "pyprodtest"
version = "0.1.0"
description = "Pytest plugin for production testing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "pytest>=8.4.2",
]

[project.entry-points.pytest11]
pyprodtest = "_pyprodtest.plugin"
